version: "3.9"
services:
  postgres-dev:
    image: postgres:12-alpine # イメージの名前
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb-dev
    ports:
      - 5432:5432